name: Unit-test check

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ventura: 
    runs-on: macos-13.4.1
    steps: 
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Switch to xcode 14.13.1
      run: sudo xcode-select -s /Applications/Xcode14.13.1.app
    - name: Show eligible build destinations for ScoreBoard
      run: xcodebuild -showdestinations -scheme ScoreBoardTest
    - name: Build and test ( iOS 16.4)
      run: xcodebuild test -scheme Earendil -destination 'platform=iOS Simulator,OS=16.4,name=iPhone 14'
